apiVersion: v1
kind: Service
metadata:
  name: monifactory
spec:
  selector:
    app: monifactory
  ports:
  - protocol: TCP
    name: "25565tcp"
    port: 25565
    targetPort: 25565
    nodePort: 31222
  - protocol: TCP
    port: 25575
    name: "25575tcp"
    targetPort: 25575
    nodePort: 31223
  type: NodePort
