apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kayro-nightly
  name: kayro-nightly
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: kayro-nightly
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kayro-nightly
    spec:
      containers:
      - image: registry.senk0.com/kayro-server:latest
        imagePullPolicy: Always
        name: kayro-server
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            ephemeral-storage: 4Gi
            memory: 8Gi
          requests:
            cpu: 100m
            memory: 2Gi
      - env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: kayro-nightly
              key: password
        image: registry.senk0.com/kayro:latest-dev
        imagePullPolicy: Always
        name: kayro
        resources:
          limits:
            cpu: "1"
            ephemeral-storage: 1Gi
            memory: 256Mi
          requests:
            cpu: 10m
            memory: 128Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 2