apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission
data:
  CONFIG_FILE: "/wg-config/wg0.conf"
  WEBPROXY_ENABLED: "false"
  LOCAL_NETWORK: "10.0.0.0/8,192.168.0.0/16,172.16.0.0/12,100.64.0.0/10,169.254.0.0/16"
  TRANSMISSION_RATIO_LIMIT: "0"
  TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
  PUID: "1000"
  PGID: "1000"
